#!/usr/bin/env python3
"""
export_tokens.py — 把平台中立的 tokens.json 导出为各平台产物。

唯一事实源: tokens.json
产物:
  - SwiftUI:  DesignTokens.swift  (Color / Font / CGFloat 常量)
  - CSS:      tokens.css          (:root CSS 变量)
  - Tailwind: tailwind.tokens.js  (可粘进 tailwind.config 的 theme.extend 片段)
  - Prompt:   style-prompt.md     (分维度反 AI-slop 风格提示词,后续写 UI 时喂给模型)

零第三方依赖(仅标准库),因为目标机器未装 pyyaml。

用法:
  python3 export_tokens.py <tokens.json> [--out <目录>] [--targets swift,css,tailwind]
默认导出全部 targets 到 tokens.json 所在目录。
"""
import argparse
import json
import os
import sys


def hex_to_rgb01(hex_str):
    """#RRGGBB -> (r, g, b) 均为 0..1,供 SwiftUI Color(red:green:blue:) 使用。"""
    h = hex_str.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        raise ValueError(f"不是合法的 #RRGGBB 颜色: {hex_str}")
    r = int(h[0:2], 16) / 255.0
    g = int(h[2:4], 16) / 255.0
    b = int(h[4:6], 16) / 255.0
    return round(r, 4), round(g, 4), round(b, 4)


def snake_to_camel(name):
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def export_swift(tokens):
    lines = [
        "// Generated by style-compass export_tokens.py — 不要手改,改 tokens.json 后重跑。",
        "import SwiftUI",
        "",
        "enum DesignTokens {",
    ]
    # 颜色
    lines.append("    enum Palette {")
    for key, val in tokens.get("color", {}).items():
        try:
            r, g, b = hex_to_rgb01(val)
        except ValueError:
            continue
        lines.append(
            f"        static let {snake_to_camel(key)} = "
            f"Color(red: {r}, green: {g}, blue: {b}) // {val}"
        )
    lines.append("    }")
    lines.append("")
    # 圆角
    lines.append("    enum Radius {")
    for key, val in tokens.get("radius", {}).items():
        lines.append(f"        static let {snake_to_camel(key)}: CGFloat = {val}")
    lines.append("    }")
    lines.append("")
    # 间距
    lines.append("    enum Spacing {")
    for key, val in tokens.get("spacing", {}).items():
        lines.append(f"        static let {snake_to_camel(key)}: CGFloat = {val}")
    lines.append("    }")
    lines.append("")
    # 字号
    typ = tokens.get("typography", {})
    lines.append("    enum FontSize {")
    for key, val in typ.get("scale", {}).items():
        safe = snake_to_camel("s_" + key) if key[0].isdigit() else snake_to_camel(key)
        lines.append(f"        static let {safe}: CGFloat = {val}")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def export_css(tokens):
    lines = [
        "/* Generated by style-compass export_tokens.py — 改 tokens.json 后重跑。 */",
        ":root {",
    ]
    for key, val in tokens.get("color", {}).items():
        lines.append(f"  --color-{key.replace('_', '-')}: {val};")
    for key, val in tokens.get("radius", {}).items():
        lines.append(f"  --radius-{key}: {val}px;")
    for key, val in tokens.get("spacing", {}).items():
        lines.append(f"  --space-{key}: {val}px;")
    typ = tokens.get("typography", {})
    if typ.get("heading_font"):
        lines.append(f"  --font-heading: {typ['heading_font']};")
    if typ.get("body_font"):
        lines.append(f"  --font-body: {typ['body_font']};")
    if typ.get("mono_font"):
        lines.append(f"  --font-mono: {typ['mono_font']};")
    for key, val in typ.get("scale", {}).items():
        lines.append(f"  --text-{key}: {val}px;")
    motion = tokens.get("motion", {})
    for key in ("duration_fast", "duration_base", "duration_slow"):
        if key in motion:
            lines.append(f"  --{key.replace('_', '-')}: {motion[key]}ms;")
    if motion.get("easing"):
        lines.append(f"  --easing: {motion['easing']};")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def export_prompt(tokens):
    """生成 style-prompt.md:以'参考谁'为最高指令 + 分维度反 slop 约束,供后续写 UI 时喂给模型。"""
    meta = tokens.get("meta", {})
    c = tokens.get("color", {})
    typ = tokens.get("typography", {})
    g = tokens.get("guardrails", {})
    name = meta.get("name", "自定义风格")
    scheme = meta.get("scheme", "light")
    # reference: 该风格参考的产品(archetype),信息量最高的指令,放最前
    reference = meta.get("reference", meta.get("based_on", ""))
    heading = typ.get("heading_font", "(见 tokens)")
    body = typ.get("body_font", "(见 tokens)")
    use = g.get("use", "(未指定,参照 tokens 数值)")
    avoid = g.get("avoid", "Inter/Roboto/默认系统字体作主视觉、紫白渐变、均匀多彩弱对比")
    ref_line = (f"参考 **{reference}** 那种美学,调动你对这类产品的全部理解自由发挥。"
                if reference else "(未指定参考产品;尽量偏离通用默认)")
    return f"""# 风格提示词 · {name}

> 由 style-compass 生成。写本工程任何 UI 前先读这份 + tokens.json。
> **最重要的一句在下面「首要指令」——先读它,再看约束。** tokens.json 是一致性的事实源,不是审美来源。

## 首要指令(信息量最高)
{ref_line}
这一句比任何颜色值都重要:让模型调动对该产品的理解,自主决定布局/密度/层次/动效,而不是机械套色值。

## 总纲(反 AI-slop)
你倾向于收敛到最安全的大众设计(俗称 AI slop)。本工程要求 **{name}**({scheme} 主题),请刻意偏离通用默认,做出有辨识度、贴合语境的设计。

## 该用什么
{use}


## 禁用什么
{avoid}

## 分维度约束
- **排版**:标题用 `{heading}`,正文用 `{body}`。**禁止**用 Inter / Roboto / Open Sans / 默认系统字体当主视觉字体。
- **色彩**:主色 `{c.get('accent', '')}`,背景 `{c.get('bg', '')}`,表面 `{c.get('surface', '')}`。承诺一套内聚配色,主色主导 + 克制强调;禁止紫白渐变、均匀铺开的多彩弱对比。
- **圆角/间距/动效**:严格取 tokens.json 中的 radius / spacing / motion 数值,保持全工程一致。
- **动效**:聚焦高光时刻(如一次编排良好的入场),而非满屏零散微交互。
- **背景/层次**:用渐变/几何/氛围营造深度,别一律纯色平铺。

## 落地时
- Web:引入生成的 tokens.css,用 `var(--color-*)` / `var(--radius-*)` 等变量,不要写死 hex。
- iOS:引入生成的 DesignTokens.swift,用 `DesignTokens.Palette.*` 等常量。
"""


def export_tailwind(tokens):
    typ = tokens.get("typography", {})
    obj = {
        "colors": tokens.get("color", {}),
        "borderRadius": {k: f"{v}px" for k, v in tokens.get("radius", {}).items()},
        "spacing": {k: f"{v}px" for k, v in tokens.get("spacing", {}).items()},
        "fontSize": {k: f"{v}px" for k, v in typ.get("scale", {}).items()},
        "fontFamily": {
            "heading": typ.get("heading_font", ""),
            "body": typ.get("body_font", ""),
            "mono": typ.get("mono_font", ""),
        },
    }
    body = json.dumps(obj, indent=2, ensure_ascii=False)
    return (
        "// Generated by style-compass — 粘进 tailwind.config.js 的 theme.extend。\n"
        "module.exports = " + body + ";\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tokens", help="tokens.json 路径")
    ap.add_argument("--out", default=None, help="产物输出目录(默认与 tokens.json 同目录)")
    ap.add_argument("--targets", default="swift,css,tailwind,prompt",
                    help="逗号分隔: swift,css,tailwind,prompt")
    args = ap.parse_args()

    with open(args.tokens, "r", encoding="utf-8") as f:
        tokens = json.load(f)

    out_dir = args.out or os.path.dirname(os.path.abspath(args.tokens))
    os.makedirs(out_dir, exist_ok=True)
    targets = [t.strip() for t in args.targets.split(",") if t.strip()]

    written = []
    if "swift" in targets:
        p = os.path.join(out_dir, "DesignTokens.swift")
        with open(p, "w", encoding="utf-8") as f:
            f.write(export_swift(tokens))
        written.append(p)
    if "css" in targets:
        p = os.path.join(out_dir, "tokens.css")
        with open(p, "w", encoding="utf-8") as f:
            f.write(export_css(tokens))
        written.append(p)
    if "tailwind" in targets:
        p = os.path.join(out_dir, "tailwind.tokens.js")
        with open(p, "w", encoding="utf-8") as f:
            f.write(export_tailwind(tokens))
        written.append(p)
    if "prompt" in targets:
        p = os.path.join(out_dir, "style-prompt.md")
        with open(p, "w", encoding="utf-8") as f:
            f.write(export_prompt(tokens))
        written.append(p)

    print("导出完成:")
    for p in written:
        print("  -", p)


if __name__ == "__main__":
    main()
